"""
Unit tests for generate_offer_bytes function (F003 Storage Abstraction).

Purpose:
    Test bytes-based Offer generation without file I/O.
    Validates F003 storage abstraction refactoring.

Expected Lifetime: Test Suite (Stable)
"""

import pytest
from io import BytesIO
from docx import Document

from scripts._5_generation_offer.offer_word import generate_offer_bytes


def extract_all_text(doc):
    """Extract text from both paragraphs and tables in Word document."""
    text_parts = []
    
    # Get paragraph text
    for paragraph in doc.paragraphs:
        if paragraph.text.strip():
            text_parts.append(paragraph.text)
    
    # Get table text
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                if cell.text.strip():
                    text_parts.append(cell.text)
    
    return "\n".join(text_parts)


class TestGenerateOfferBytes:
    """Test generate_offer_bytes function for F003 storage abstraction."""
    
    @pytest.fixture
    def valid_offer_data(self):
        """Fixture providing valid minimal Offer data."""
        return {
            "angebots_metadata": {
                "angebots_id": "GDJOB-12345",
                "anbieter": "Orange Business",
                "kunde": "Acme Corporation",
                "datum": "2026-01-27",
                "ansprechpartner": {
                    "name": "John Manager",
                    "rolle": "HR Manager",
                    "kontakt": "john.manager@acme.com"
                }
            },
            "stellenbezug": {
                "rollenbezeichnung": "Senior Java Developer",
                "organisationseinheit": "IT Development",
                "kurzkontext": "Wir freuen uns, Ihnen einen qualifizierten Kandidaten für die Position als Senior Java Developer vorzuschlagen."
            },
            "kandidatenvorschlag": {
                "name": "Max Mustermann",
                "angebotene_rolle": "Senior Java Developer",
                "eignungs_summary": "Hochqualifizierter Entwickler mit 10 Jahren Erfahrung"
            },
            "cv_daten": {
                "Vorname": "Max",
                "Nachname": "Mustermann"
            },
            "einsatzkonditionen": {
                "pensum": "100%",
                "verfuegbarkeit": "01.03.2026",
                "stundensatz": "CHF 150.-",
                "subunternehmen": "-"
            },
            "kriterien_abgleich": {
                "muss_kriterien": [
                    {
                        "kriterium": "Java 17+",
                        "erfuellt": "erfüllt",
                        "begruendung": "10 Jahre Java-Erfahrung"
                    }
                ],
                "soll_kriterien": [
                    {
                        "kriterium": "Spring Boot",
                        "erfuellt": "erfüllt",
                        "begruendung": "Mehrjährige Erfahrung"
                    }
                ],
                "weitere_kriterien": [],
                "soft_skills": [
                    {
                        "kriterium": "Teamfähigkeit",
                        "erfuellt": "erfüllt",
                        "begruendung": "Langjährige Teamerfahrung"
                    }
                ]
            },
            "gesamtbeurteilung": {
                "zusammenfassung": "Der Kandidat ist **hervorragend qualifiziert** und erfüllt alle Anforderungen.",
                "mehrwert_fuer_kunden": [
                    "Sofortige Produktivität durch umfassende Erfahrung",
                    "Starke technische Fähigkeiten",
                    "Ausgezeichnete Kommunikationsfähigkeiten"
                ],
                "empfehlung": "Wir **empfehlen den Kandidaten uneingeschränkt**."
            }
        }
    
    def test_generate_offer_bytes_returns_bytes_and_filename(self, valid_offer_data):
        """Test that generate_offer_bytes returns bytes and filename."""
        result = generate_offer_bytes(valid_offer_data, language="de")
        
        assert isinstance(result, tuple)
        assert len(result) == 2
        
        docx_bytes, filename = result
        assert isinstance(docx_bytes, bytes)
        assert isinstance(filename, str)
        assert len(docx_bytes) > 0
        assert filename.endswith(".docx")
    
    def test_filename_contains_candidate_name(self, valid_offer_data):
        """Test that filename includes candidate's name."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        assert "Max" in filename
        assert "Mustermann" in filename
        assert filename == "offer_Max_Mustermann.docx"
    
    def test_generated_bytes_are_valid_docx(self, valid_offer_data):
        """Test that generated bytes can be loaded as valid Word document."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        # Try to load bytes as Document
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        
        # Verify document has content
        assert len(doc.paragraphs) > 0 or len(doc.tables) > 0
        
        # Check for offer ID in document
        doc_text = extract_all_text(doc)
        assert "GDJOB-12345" in doc_text
    
    def test_language_de(self, valid_offer_data):
        """Test German language output."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        # Load and check for German text
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Should contain German content
        assert "Acme Corporation" in doc_text  # Customer name
        assert "Senior Java Developer" in doc_text  # Role
    
    def test_language_en(self, valid_offer_data):
        """Test English language output (basic structure check)."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="en")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Basic check that document was generated
        assert len(doc_text) > 100
    
    def test_candidate_data_in_offer(self, valid_offer_data):
        """Test that candidate data is present in offer."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Check for candidate role and summary (name not shown in offer body, only in filename)
        assert "Senior Java Developer" in doc_text
        assert "Hochqualifizierter Entwickler" in doc_text
    
    def test_criteria_match_in_offer(self, valid_offer_data):
        """Test that criteria matching is included."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Check for criteria
        assert "Java" in doc_text or "Spring" in doc_text
    
    def test_conditions_in_offer(self, valid_offer_data):
        """Test that employment conditions are included."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Check for conditions
        assert "100%" in doc_text  # Pensum
        assert "01.03.2026" in doc_text or "CHF" in doc_text  # Availability or rate
    
    def test_assessment_in_offer(self, valid_offer_data):
        """Test that assessment section is included."""
        docx_bytes, filename = generate_offer_bytes(valid_offer_data, language="de")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Check for assessment text (without bold markers)
        assert "hervorragend" in doc_text or "qualifiziert" in doc_text or "empfehlen" in doc_text

