#!/usr/bin/env python3
"""
Universal pre-commit hook installer for all platforms (Windows, macOS, Linux)
Replaces platform-specific install scripts (install_hooks.sh, install_hooks.bat)
"""

import os
import sys
import stat
import shutil
from pathlib import Path


def setup_pre_commit_hook():
    """
    Install pre-commit hook for all platforms
    Works on Windows, macOS, and Linux
    """
    repo_root = Path(__file__).parent.parent
    hooks_dir = repo_root / '.git' / 'hooks'
    pre_commit_hook = hooks_dir / 'pre-commit'

    print("\n" + "=" * 70)
    print("🔧 Setting up pre-commit hook...")
    print("=" * 70)

    # Ensure hooks directory exists
    hooks_dir.mkdir(parents=True, exist_ok=True)
    print(f"✅ Hooks directory ready: {hooks_dir}")

    # Create hook script
    # Use Python shebang for cross-platform compatibility
    hook_content = f'''#!/usr/bin/env python3
"""Pre-Commit Hook - Auto-generated by setup_hooks.py"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.pre_commit_hook import main
sys.exit(main())
'''

    # Write hook file
    pre_commit_hook.write_text(hook_content, encoding='utf-8')
    print(f"✅ Hook file created: {pre_commit_hook}")

    # Make executable on Unix-like systems
    if sys.platform != 'win32':
        st = pre_commit_hook.stat()
        pre_commit_hook.chmod(st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print("✅ Hook made executable (Unix/macOS)")
    else:
        print("✅ Hook is ready for Windows")

    print("\n" + "=" * 70)
    print("✨ Pre-commit hook setup complete!")
    print("=" * 70)
    print("\n📝 Usage:")
    print("  Commits will now automatically:")
    print("  1. Validate structured metadata (icon, feature_name, etc.)")
    print("  2. Detect unused files (>180 days old)")
    print("  3. Generate commit_metadata.json for app consumption")
    print("\n💡 Commit message format:")
    print("  ✨(feature): Feature Name - Description")
    print("  🐛(bug): Bug fix description")
    print("  📝(docs): Documentation update")
    print("  ♻️(refactor): Refactoring work")
    print("  🧪(test): Test additions/changes")
    print("  🔧(chore): Maintenance tasks")
    print("\n" + "=" * 70 + "\n")

    return True


def uninstall_pre_commit_hook():
    """Remove pre-commit hook"""
    repo_root = Path(__file__).parent.parent
    pre_commit_hook = repo_root / '.git' / 'hooks' / 'pre-commit'

    if pre_commit_hook.exists():
        pre_commit_hook.unlink()
        print("✅ Pre-commit hook removed")
        return True
    else:
        print("ℹ️ Pre-commit hook not found")
        return False


def check_hook_status():
    """Check if hook is installed"""
    repo_root = Path(__file__).parent.parent
    pre_commit_hook = repo_root / '.git' / 'hooks' / 'pre-commit'

    if pre_commit_hook.exists():
        is_executable = os.access(pre_commit_hook, os.X_OK)
        status = "✅ Installed and executable" if is_executable else "⚠️ Installed but not executable"
        print(f"\nPre-commit hook status: {status}")
        print(f"Location: {pre_commit_hook}")
        return True
    else:
        print("\n❌ Pre-commit hook not installed")
        print(f"Expected location: {pre_commit_hook}")
        return False


if __name__ == '__main__':
    if len(sys.argv) > 1:
        if sys.argv[1] == 'uninstall':
            uninstall_pre_commit_hook()
        elif sys.argv[1] == 'status':
            check_hook_status()
        else:
            print(f"Unknown command: {sys.argv[1]}")
            print("Usage: python setup_hooks.py [install|uninstall|status]")
            sys.exit(1)
    else:
        # Default: install
        try:
            setup_pre_commit_hook()
        except Exception as e:
            print(f"❌ Error setting up hook: {e}", file=sys.stderr)
            sys.exit(1)
