"""
Unit tests for generate_cv_bytes function (F003 Storage Abstraction).

Purpose:
    Test bytes-based CV generation without file I/O.
    Validates F003 storage abstraction refactoring.

Expected Lifetime: Test Suite (Stable)
"""

import pytest
import json
from io import BytesIO
from docx import Document

from scripts._2_extraction_cv.cv_word import generate_cv_bytes


def extract_all_text(doc):
    """Extract text from both paragraphs and tables in Word document."""
    text_parts = []
    
    # Get paragraph text
    for paragraph in doc.paragraphs:
        if paragraph.text.strip():
            text_parts.append(paragraph.text)
    
    # Get table text
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                if cell.text.strip():
                    text_parts.append(cell.text)
    
    return "\n".join(text_parts)


class TestGenerateCVBytes:
    """Test generate_cv_bytes function for F003 storage abstraction."""
    
    @pytest.fixture
    def valid_cv_data(self):
        """Fixture providing valid minimal CV data."""
        return {
            "Vorname": "Max",
            "Nachname": "Mustermann",
            "Hauptrolle": {
                "Titel": "Senior Developer",
                "Beschreibung": "Experienced software engineer with cloud expertise"
            },
            "Nationalität": "Schweiz",
            "Ausbildung": "Master of Science in Computer Science",
            "Kurzprofil": "Max verfügt über 10 Jahre Erfahrung in der Softwareentwicklung mit Fokus auf Cloud-native Architekturen. Er hat zahlreiche erfolgreiche Projekte geleitet und ist erfahren in agilen Methoden.",
            "Fachwissen_und_Schwerpunkte": [
                {
                    "Kategorie": "Projektmethodik",
                    "Inhalt": ["Scrum", "Kanban", "HERMES"]
                },
                {
                    "Kategorie": "Tech Stack",
                    "Inhalt": ["Java", "Python", "Docker", "Kubernetes"]
                },
                {
                    "Kategorie": "Weitere Fähigkeiten / Skills",
                    "Inhalt": ["Leadership", "Coaching", "Architecture"]
                }
            ],
            "Aus_und_Weiterbildung": [
                {
                    "Zeitraum": "09/2010 - 06/2015",
                    "Institution": "ETH Zürich",
                    "Abschluss": "Master of Science in Computer Science"
                }
            ],
            "Trainings_und_Zertifizierungen": [
                {
                    "Zeitraum": "03/2020",
                    "Institution": "AWS",
                    "Titel": "AWS Certified Solutions Architect"
                }
            ],
            "Sprachen": [
                {"Sprache": "Deutsch", "Level": "Muttersprache"},
                {"Sprache": "Englisch", "Level": "Verhandlungssicher"}
            ],
            "Ausgewählte_Referenzprojekte": [
                {
                    "Kunde": "Acme Corporation",
                    "Zeitraum": "01/2022 - 12/2023",
                    "Rolle": "Lead Developer",
                    "Tätigkeiten": [
                        "Architektur und Implementierung Cloud-Plattform",
                        "Teamleitung (5 Entwickler)",
                        "DevOps Pipeline Aufbau"
                    ],
                    "Technologien": "Java, Spring Boot, AWS, Kubernetes",
                    "Methodik": "Scrum, CI/CD"
                }
            ]
        }
    
    def test_generate_cv_bytes_returns_bytes_and_filename(self, valid_cv_data):
        """Test that generate_cv_bytes returns bytes and filename."""
        result = generate_cv_bytes(valid_cv_data, language="de")
        
        assert isinstance(result, tuple)
        assert len(result) == 2
        
        docx_bytes, filename = result
        assert isinstance(docx_bytes, bytes)
        assert isinstance(filename, str)
        assert len(docx_bytes) > 0
        assert filename.endswith(".docx")
    
    def test_filename_contains_candidate_name(self, valid_cv_data):
        """Test that filename includes candidate's name."""
        docx_bytes, filename = generate_cv_bytes(valid_cv_data, language="de")
        
        assert "Max" in filename
        assert "Mustermann" in filename
        assert filename == "cv_Max_Mustermann.docx"
    
    def test_generated_bytes_are_valid_docx(self, valid_cv_data):
        """Test that generated bytes can be loaded as valid Word document."""
        docx_bytes, filename = generate_cv_bytes(valid_cv_data, language="de")
        
        # Try to load bytes as Document
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        
        # Verify document has content
        assert len(doc.paragraphs) > 0
        
        # Check for candidate name in document
        doc_text = "\n".join([p.text for p in doc.paragraphs])
        assert "Max Mustermann" in doc_text
    
    def test_invalid_data_raises_valueerror(self):
        """Test that invalid CV data raises ValueError."""
        invalid_data = {
            "Vorname": "Test"
            # Missing required fields
        }
        
        with pytest.raises(ValueError) as exc_info:
            generate_cv_bytes(invalid_data, language="de")
        
        assert "validation failed" in str(exc_info.value)
    
    def test_language_de(self, valid_cv_data):
        """Test German language output."""
        docx_bytes, filename = generate_cv_bytes(valid_cv_data, language="de")
        
        # Load and check for German text
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Should contain German section headers (from translations)
        assert "Schweiz" in doc_text  # Nationalität field
    
    def test_language_en(self, valid_cv_data):
        """Test English language output."""
        docx_bytes, filename = generate_cv_bytes(valid_cv_data, language="en")
        
        # Should still generate valid document
        assert isinstance(docx_bytes, bytes)
        assert len(docx_bytes) > 0
    
    def test_handles_missing_optional_data(self, valid_cv_data):
        """Test that optional fields can be empty lists."""
        minimal_data = valid_cv_data.copy()
        minimal_data["Trainings_und_Zertifizierungen"] = []
        minimal_data["Ausgewählte_Referenzprojekte"] = []
        
        docx_bytes, filename = generate_cv_bytes(minimal_data, language="de")
        
        # Should still generate valid document
        assert isinstance(docx_bytes, bytes)
        assert len(docx_bytes) > 0
    
    def test_project_activities_rendered(self, valid_cv_data):
        """Test that project activities (Tätigkeiten) are included."""
        docx_bytes, filename = generate_cv_bytes(valid_cv_data, language="de")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Check for project activity
        assert "Cloud-Plattform" in doc_text or "Teamleitung" in doc_text
    
    def test_multiple_languages_in_cv(self, valid_cv_data):
        """Test CV with multiple language entries."""
        docx_bytes, filename = generate_cv_bytes(valid_cv_data, language="de")
        
        docx_io = BytesIO(docx_bytes)
        doc = Document(docx_io)
        doc_text = extract_all_text(doc)
        
        # Should contain both languages
        assert "Deutsch" in doc_text
        assert "Englisch" in doc_text
